server:
  port: 8080
  tomcat:
    threads:
      max: 200
    max-connections: 8192
    accept-count: 100

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: log-collector

logging:
  level:
    root: INFO
    com.example.logcollector: DEBUG
  file:
    name: logs/application.log